<?php

use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Foundation\Http\Middleware\ValidateCsrfToken;
use App\Console\Commands\MakeMigrationCommand;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\Storage;
use Illuminate\Support\Str;
use App\Http\Controllers\AController;
use App\Http\Controllers\PatelController;
use App\Http\Controllers\Patel1Controller;
use App\Http\Controllers\Patel2Controller;
use App\Http\Controllers\ParthController;
use App\Http\Controllers\MaanController;
use App\Http\Controllers\Maan2Controller;
use App\Http\Controllers\TestController;
use App\Http\Controllers\AAAController;
use App\Http\Controllers\BBBController;
use App\Http\Controllers\TestingController;
use App\Http\Controllers\NandController;
use App\Http\Controllers\TryController;
use App\Http\Controllers\Try2Controller;
use App\Http\Controllers\try2;
use App\Http\Controllers\Try3Controller;
use App\Http\Controllers\try3;
use App\Http\Controllers\Try4Controller;
use App\Http\Controllers\Try5Controller;
use App\Http\Controllers\Try6Controller;
use App\Http\Controllers\Try7Controller;
use App\Http\Controllers\Maan_table10Controller;
use App\Http\Controllers\Test123Controller;
use App\Http\Controllers\Test1234Controller;
use App\Http\Controllers\Test_tableController;
use App\Http\Controllers\Test_table2Controller;
use App\Http\Controllers\Test3Controller;
use App\Http\Controllers\Test_table4Controller;
use App\Http\Controllers\Test_table5Controller;
use App\Http\Controllers\Tests01Controller;
use App\Http\Controllers\Test02Controller;
use App\Http\Controllers\Test03Controller;
use App\Http\Controllers\Test04Controller;
use App\Http\Controllers\Test05Controller;
use App\Http\Controllers\Test06Controller;
use App\Http\Controllers\Test07Controller;
use App\Http\Controllers\Test08Controller;
use App\Http\Controllers\Test09Controller;
use App\Http\Controllers\Test11Controller;
use App\Http\Controllers\Demo10Controller;
use App\Http\Controllers\Demo12Controller;
use App\Http\Controllers\Demo13Controller;
use App\Http\Controllers\Demo14Controller;
use App\Http\Controllers\Testing1Controller;
use App\Http\Controllers\Testing12Controller;
use App\Http\Controllers\Testing12345Controller;
use App\Http\Controllers\QwertController;
use App\Http\Controllers\Demo132Controller;
use App\Http\Controllers\Demo132ControllerController;
// use App\Http\Controllers\AaaController;
use App\Http\Controllers\Demo15Controller;
use App\Http\Controllers\TttController;
use App\Http\Controllers\Demo17Controller;
use App\Http\Controllers\Demo18Controller;
use App\Http\Controllers\Demo19Controller;
use App\Http\Controllers\Demo20Controller;
use App\Http\Controllers\Demo21Controller;
use App\Http\Controllers\Demo22Controller;
use App\Http\Controllers\Demo23Controller;
use App\Http\Controllers\Demo24Controller;
use App\Http\Controllers\Demo25Controller;
use App\Http\Controllers\Table_nameController;
use App\Http\Controllers\SdfController;
use App\Http\Controllers\Demo100Controller;
use App\Http\Controllers\Demo101Controller;
use App\Http\Controllers\Demo1000Controller;
use App\Http\Controllers\TryyController;
use App\Http\Controllers\Demo30Controller;
use App\Http\Controllers\Demo1223Controller;
use App\Http\Controllers\AsdfController;
use App\Http\Controllers\Demo1234Controller;
use App\Http\Controllers\Demo011Controller;
use App\Http\Controllers\TargetController;
use App\Http\Controllers\EeeController;
// [USE_CONTROLLERS]


Route::get('/', function () {
    return view('welcome');
});

Route::redirect('/', '/Home');

Route::resource('/Home', HomeController::class);

// Route::resource('patel', PatelController::class);
// Route::resource('Patel1Controller', Patel1Controller::class);
// Route::resource('Patel2Controller', Patel2Controller::class);
// Route::resource('ParthController', ParthController::class);
// Route::resource('MaanController', MaanController::class);
// Route::resource('Maan2Controller', Maan2Controller::class);
// Route::resource('TestController', TestController::class);
// Route::resource('AAAController', AAAController::class);
// Route::resource('BBBController', BBBController::class);
// Route::resource('TestingController', TestingController::class);
// Route::resource('NandController', NandController::class);
// Route::resource('TryController', TryController::class);
// Route::resource('Try2Controller', Try2Controller::class);
// Route::resource('Try3Controller', Try3Controller::class);
// Route::resource('Try4Controller', Try4Controller::class);
// Route::resource('Try5Controller', Try5Controller::class);
// Route::resource('Try6Controller', Try6Controller::class);
// Route::resource('Try7Controller', Try7Controller::class);
// Route::resource('Maan_table10Controller', Maan_table10Controller::class);
// Route::resource('Test123Controller', Test123Controller::class);
// Route::resource('Test1234Controller', Test1234Controller::class);
// Route::resource('Test_tableController', Test_tableController::class);
// Route::resource('Test_table2Controller', Test_table2Controller::class);
// Route::resource('Test3Controller', Test3Controller::class);
// Route::resource('Test_table4Controller', Test_table4Controller::class);
// Route::resource('Test_table5Controller', Test_table5Controller::class);
// Route::resource('Tests01Controller', Tests01Controller::class);
// Route::resource('Test02Controller', Test02Controller::class);
// Route::resource('Test03Controller', Test03Controller::class);
// Route::resource('Test04Controller', Test04Controller::class);
// Route::resource('Test05Controller', Test05Controller::class);
// Route::resource('Test06Controller', Test06Controller::class);
// Route::resource('Test07Controller', Test07Controller::class);
// Route::resource('Test08Controller', Test08Controller::class);
// Route::resource('Test09Controller', Test09Controller::class);
// Route::resource('Test11Controller', Test11Controller::class);
// Route::resource('Demo10Controller', Demo10Controller::class);
// Route::resource('Demo12Controller', Demo12Controller::class);
// Route::resource('Demo13Controller', Demo13Controller::class);
Route::resource('Demo14Controller', Demo14Controller::class);
Route::resource('Testing1Controller', Testing1Controller::class);
Route::resource('Testing12Controller', Testing12Controller::class);
Route::resource('Testing12345Controller', Testing12345Controller::class);
Route::resource('QwertController', QwertController::class);
Route::resource('Demo132Controller', Demo132Controller::class);
Route::resource('Demo132ControllerController', Demo132ControllerController::class);
Route::resource('AaaController', AaaController::class);
Route::resource('Demo15Controller', Demo15Controller::class);
Route::resource('TttController', TttController::class);
Route::resource('Demo17Controller', Demo17Controller::class);
Route::resource('Demo18Controller', Demo18Controller::class);
Route::resource('Demo19Controller', Demo19Controller::class);
Route::resource('Demo20Controller', Demo20Controller::class);
Route::resource('Demo21Controller', Demo21Controller::class);
Route::resource('Demo22Controller', Demo22Controller::class);
Route::resource('Demo23Controller', Demo23Controller::class);
Route::resource('Demo24Controller', Demo24Controller::class);
Route::resource('Demo25Controller', Demo25Controller::class);
Route::resource('Table_nameController', Table_nameController::class);
Route::resource('SdfController', SdfController::class);
Route::resource('Demo100Controller', Demo100Controller::class);
Route::resource('Demo101Controller', Demo101Controller::class);
Route::resource('Demo1000Controller', Demo1000Controller::class);
Route::resource('TryyController', TryyController::class);
Route::resource('Demo30Controller', Demo30Controller::class);
Route::resource('Demo1223Controller', Demo1223Controller::class);
Route::resource('AsdfController', AsdfController::class);
Route::resource('Demo1234Controller', Demo1234Controller::class);
Route::resource('Demo011Controller', Demo011Controller::class);
Route::resource('TargetController', TargetController::class);
Route::resource('EeeController', EeeController::class);
// [ROUTE_CONTROLLERS]
